// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ObjectsColumns holds the columns for the "objects" table.
	ObjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bucket_name", Type: field.TypeString},
		{Name: "object_name", Type: field.TypeString},
		{Name: "storage_path", Type: field.TypeString, Unique: true},
		{Name: "content_type", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "etag", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ObjectsTable holds the schema information for the "objects" table.
	ObjectsTable = &schema.Table{
		Name:       "objects",
		Columns:    ObjectsColumns,
		PrimaryKey: []*schema.Column{ObjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "object_id_bucket_name_object_name",
				Unique:  true,
				Columns: []*schema.Column{ObjectsColumns[0], ObjectsColumns[1], ObjectsColumns[2]},
			},
		},
	}
	// ObjectMetadataColumns holds the columns for the "object_metadata" table.
	ObjectMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "object_id", Type: field.TypeInt, Unique: true},
	}
	// ObjectMetadataTable holds the schema information for the "object_metadata" table.
	ObjectMetadataTable = &schema.Table{
		Name:       "object_metadata",
		Columns:    ObjectMetadataColumns,
		PrimaryKey: []*schema.Column{ObjectMetadataColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "object_metadata_objects_metadata",
				Columns:    []*schema.Column{ObjectMetadataColumns[5]},
				RefColumns: []*schema.Column{ObjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "objectmetadata_object_id_key",
				Unique:  true,
				Columns: []*schema.Column{ObjectMetadataColumns[5], ObjectMetadataColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ObjectsTable,
		ObjectMetadataTable,
	}
)

func init() {
	ObjectMetadataTable.ForeignKeys[0].RefTable = ObjectsTable
}
