// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Object is the predicate function for object builders.
type Object func(*sql.Selector)

// ObjectMetadata is the predicate function for objectmetadata builders.
type ObjectMetadata func(*sql.Selector)
